### ISSUE TITLE
Not working on local development

### ISSUE THREAD

**Issue by Tropicalista** [JeffreyWay/Laravel-4-Generators#447] opened 2015-02-04 23:14 UTC
If I add generators to local providers app crashes, simply commented out the generators class all works perfectly.

    'providers' => array(

	   
	    'Barryvdh\Debugbar\ServiceProvider', // Debugger
        //'Way\Generators\GeneratorsServiceProvider', // Generator
	    
    ),

**Comment by mikeerickson** [comment] 2015-02-05 02:30
What version of Laravel are you using?

If L5, it is *currently* not working.

**Comment by jasonherndon** [comment] 2015-02-05 20:38
I'm running into the same problem as well. Is that what the "Build:error" tag on the front of the github page is for?

**Comment by Tropicalista** [comment] 2015-02-05 23:42
I'm on laravel 4.2. I use confide and entrust, not sure if there is some conflicts...

**Comment by daltonamitchell** [comment] 2015-02-07 21:02
Having the same issue. It looks like the `boot()` method is failing in the Service Provider
```
    /**
     * Booting
     */
    public function boot()
    {
        $this->package('way/generators');
    }
```
Looks like `Illuminate\Support\ServiceProvider` no longer has a `package()` reference so I changed to `$this->app->package('way/generators')` as a temp fix. I just started a new L5 today. I wonder if this is a bug from a recent change.

**Comment by pandasauce** [comment] 2015-02-07 22:12
This is a duplicate of #433 #436 #437 #444

No permanent solution as of yet.

**Comment by phirschybar** [comment] 2015-02-08 02:59
I think $this->package() is not needed any more. At least it is no longer in the Laravel docs. The boot() method seems to be only for publishing assets, migration files, public files, config files, etc.

**Closed** 2015-02-26 05:56 UTC
